### ISSUE TITLE
Missing files on 1.6.0

### ISSUE THREAD

**Issue by ajturner** [greglu/hbase-stargate#2]
Trying to gem build the 1.6.0 branch and I get this:

] gem build hbase-stargate.gemspec 
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["lib/stargate/model/region_descriptor.rb", "spec/hbase-stargate/model/region_descriptor_spec.rb"] are not files

**Comment by greglu** [comment]
The 1.6.0 branch didn't get the gemspec rebuilt for it. You can try a version bump (just make sure to delete the gem when I actually release 1.6.0) and run "rake gemspec" and then "rake build". Otherwise, it wasn't meant to be built yet.
