### ISSUE TITLE
Create Table fails on HBase 0.20.6 and hbase-stargate master

### ISSUE THREAD

**Issue by ajturner** [greglu/hbase-stargate#3]
Using Master branch, I'm trying to create a table, and I get:

irb(main):008:0> table = client.create_table("table2", 'data')
Stargate::TableFailCreateError: 503 "Service Unavailable"
    from /usr/local/lib/ruby/gems/1.8/gems/hbase-stargate-1.5.1/lib/stargate/operation/table_operation.rb:43:in `create_table'
    from (irb):8
irb(main):009:0> exit
## 

confirmed that tables can be created in the console.

**Comment by greglu** [comment]
I can't replicate this problem. I've upgraded HBase to 0.90.4 and updated this library as well. Stargate is actually just the default rest server now and can be started up with:

> $HBASE_HOME/bin/hbase rest start

Can you try creating the table again, and watch the output of the REST server log (keep the previous command open in a console somewhere)? If you still can't create the table, please reopen this case and post the relevant log entries here.

Thanks!

**Comment by ajturner** [comment]
Thanks - will do that.
