### ISSUE TITLE
The application should be able to stream rows from a scanner

### ISSUE THREAD

**Issue by joshuanapoli** [greglu/hbase-stargate#6]
ScannerOperation.get_rows loads the entire result into memory. I would like to work with ranges that are larger than memory; I could do this if there were a ScannerOperation.get_each_row method. It should load batches, yielding rows one-by-one to the block.

**Comment by greglu** [comment]
You're right. I've implemented a new method in the client called each_row and it works like so:

```
client.each_row(scanner) do |row|
  # row is an instance of Stargate::Model::Row
  puts "#{row.name} => #{row.columns}"
end
```

This will now only keep the batch size number of rows around in memory.

I've rolled this change out for version 1.6.1.
