### ISSUE TITLE
How to convert StargateObject to xml

### ISSUE THREAD

**Issue by ganeshtripathi** [greglu/hbase-stargate#9]
how to convert fetched data from hbase (in RoR) using Stargate in to xml

**Comment by greglu** [comment]
Could you clarify this question please? The whole point of hbase-stargate is to provide a Ruby API for working with the data in HBase. It does this by translating the JSON/XML/Protobuf data coming from the HBase REST server and turns it into Ruby objects/methods.

If you needed the data in XML, then I suggest you get the data from the HBase REST server directly and bypass this library altogether. Open me up another case if you believe there's actually an issue with the project.
